use_default_settings:
  engines:
    keep_only:
      - bing
      - google
      - yandex
      - naver
      - yahoo
      - seznam
      - github
      - stackoverflow

engines:
  - name: bing
  - name: google
  - name: yandex
  - name: naver
  - name: yahoo
  - name: seznam
  - name: github
  - name: stackoverflow

server:
  secret_key: "ulizosecretkeyyakoapahapa12345"
  limiter: false
  public_instance: false

search:
  formats:
    - html
    - json

ui:
  static_use_hash: true
